name: parallel-python
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - pip>=20
  - numba>=0.55
  - numpy>=1.19
  - scipy>=1.5
  - dask[complete]>=2.20
  - pytest>=6
#  - imagemagick
  - ffmpeg
  - matplotlib
  - graphviz
  - jupyterlab
  - nltk
  - pip:
     - snakemake>=5.28
     - graphviz
#     - -r file:requirements.txt
