name: parallel-python
channels:
  - defaults
dependencies:
  - python==3.14
  - numba
  - numpy
  - scipy
  - dask[complete]
  - pytest
  - matplotlib
  - graphviz
  - jupyterlab
  - polars
  - xarray
  - geopandas
  - py-spy
  - pip
  - pip:
    - memory-profiler

