[project]
name = "parallel-python-workshop"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "dask[complete]>=2026.3.0",
    "geopandas>=1.1.3",
    "jupyterlab>=4.5.7",
    "matplotlib>=3.10.9",
    "memory-profiler>=0.61.0",
    "numba>=0.65.1",
    "numpy>=2.4.6",
    "pandas>=3.0.3",
    "polars>=1.40.1",
    "pooch>=1.9.0",
    "py-spy>=0.4.2",
    "pytest>=9.0.3",
    "scipy>=1.17.1",
    "tqdm>=4.67.3",
    "xarray>=2026.4.0",
]

[tool.setuptools]
packages = []

[tool.pytest]
testpaths = ["test"]

